version: '3'


services:
  # app
  ifttt_to_bluesky_api:
    container_name: ifttt_to_bluesky_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV
      - TEST_HANDLE
      - TEST_APP_PASSWORD
    ports:
      - 8080:8080
    volumes:
      # for container debug
      - .:/app


